site_name: Operationally Simple Web Sites
site_url: https://steveasleep.com/ordinaryguide/
site_author: Steve Landey
site_description: >-
  How to make web sites that are easy and cheap to operate

repo_name: irskep/ordinaryguide
repo_url: https://github.com/irskep/ordinaryguide
copyright: Copyright &copy; 2023 Steve Landey

theme:
  name: material
  icon:
    logo: material/code-tags
  palette:
    primary: amber
    accent: blue
  features:
    - navigation.expand
    - navigation.sections
    - navigation.tracking
    - navigation.top
    - navigation.footer
    - toc.integrate

extra:
  social:
    - icon: fontawesome/brands/mastodon
      link: https://mastodon.gamedev.place/@irskep
    - icon: fontawesome/brands/github
      link: https://github.com/irskep

extra_css:
  - stylesheets/extra.css

plugins:
  - search
  - git-revision-date-localized

markdown_extensions:
  - smarty:
      smart_angled_quotes: True
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - tables
  - pymdownx.betterem
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.highlight:
      anchor_linenums: true
      pygments_lang_class: true
      auto_title: true
      line_spans: __span

nav:
  - Home: index.md
  - Choosing Tools:
      - Overview: stacks/index.md
      - Backend: stacks/backend.md
      - Frontend: stacks/frontend.md
